#!/bin/bash -x

# ---- install ----
install -m 0644 .vimrc $HOME
install -m 0644 .gitconfig $HOME
install -m 0644 .bashrc $HOME
rsync -avr .ssh/config* $HOME/.ssh/ &&
    chmod 0644  $HOME/.ssh/config
rsync -avr .vim/rc $HOME/.vim/

