#!/bin/bash

BASE="Fedora release 32"

grep -q "$BASE" /etc/redhat-release || exit 1

# ---- REPO ----
sudo dnf install -y \
  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install -y \
  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm


# ---- PACKAGE ---- 
sudo dnf install -y \
    vim \
    blender.x86_64
    vlc \
    vim-X11 \
    transmission \
 
