#!/bin/bash -e

BASE="Fedora release 32"

grep -q "$BASE" /etc/redhat-release || exit 1

# ---- HOSTNAME ----
echo -n "HOSTNAME ?= "
read hostname
test -n "$hostname" && sudo hostnamectl set-hostname ${hostname}
echo '# ---- HOSTNAME ----'


# ---- DISK ----
# TODO: determine root disk
echo -n "Extend to new part end [GB] ?= "
read part_end
if [[ "$part_end" =~ ^[0-9]+$ ]] ; then
    part_end=${part_end}GB
else
    part_end="100%"
fi
sudo parted /dev/sda -s resizepart 3 "$part_end"
sudo pvresize /dev/sda3
set +e
sudo lvextend -l +100%FREE /dev/fedora_zero/root
set -e
sudo resize2fs /dev/fedora_zero/root
df -h
echo '# ---- DISK ----'


# ---- REPO ----
sudo dnf install -y \
  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install -y \
  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
echo '# ---- REPO ----'


# ---- PACKAGE ---- 
sudo dnf update -y
sudo dnf install -y \
    freecad \
    ffmpeg \
    ffmpeg-devel \
    gnome-tweaks \
    libvirt-client \
    retext \
    remmina \
    virt-manager \
    inkscape \
    jq \
    vim \
    blender \
    vlc \
    vim-X11 \
    transmission 
dnf clean all

pip3 install --no-cache-dir  --user yq
echo '# ---- PACKAGE ----'


# ---- CONFIG ----
cp -b \
    .bashrc \
    .gitconfig \
    .vimrc \
     ~/ 
echo '# ---- CONFIG ----'


# ---- FACILITY ----
