#!/bin/bash -xe

MOUNTPOINT=$1
VIRTUAL=$2
DEVICE_PATH=$(mount | grep "on ${MOUNTPOINT} " | awk '{print $1}')
MKGIT=./mkgit
test -n "$DEVICE_PATH" || exit 1
UUID=$(blkid  -o  value $DEVICE_PATH | head -1)
test -n "$UUID" || exit 1

STATUS_FILE=$(readlink -f ./${MKGIT}/fs-${UUID})



#META
AVAIL=$(df -h --output=avail  $MOUNTPOINT | tail -1)
USED=$(df -h --output=used  $MOUNTPOINT | tail -1)
SIZE=$(df -h --output=size  $MOUNTPOINT | tail -1)

printf '{"Size": "%s"  ,  "Used": "%s"  ,  "Avail": "%s"  ,  "Virtual": "%s"}\n' \
    $SIZE \
    $USED \
    $AVAIL \
    $VIRTUAL \
    > $STATUS_FILE


#LISTING
cd $MOUNTPOINT
find >> $STATUS_FILE

#STATUS
head -1 $STATUS_FILE | jq

