#!/bin/bash -xe


# ---- DEVICE ID
MOUNTPOINT=$1
DEVICE_PATH=$(mount | grep "on ${MOUNTPOINT} " | awk '{print $1}')
MKGIT=./mkgit
mkdir -p $MKGIT
test -n "$DEVICE_PATH" || exit 1
UUID=$(blkid  -o  value $DEVICE_PATH | head -1)
test -n "$UUID" || exit 1
STATUS_FILE=$(readlink -f ./${MKGIT}/fs-${UUID})


# ---- META FIELDS
SIZE=$(df -h --output=size  $MOUNTPOINT | tail -1)
USED=$(df -h --output=used  $MOUNTPOINT | tail -1)
AVAIL=$(df -h --output=avail  $MOUNTPOINT | tail -1)
DATE=$(date -u '+%Y-%m-%dT%H-%M-%SZ')
META_DIR=$MOUNTPOINT/.meta.${UUID}


# ---- PRINT
FORMAT_STR='{
    "Size": "%s",
    "Used": "%s",
    "Avail": "%s",
    "Update": "%s"
    }\n'
printf "$FORMAT_STR" \
    $SIZE \
    $USED \
    $AVAIL \
    $DATE \
    | jq --compact-output  >  $STATUS_FILE

cat $META_DIR/json | jq --compact-output  >> $STATUS_FILE 


# ---- LISTING
cd $MOUNTPOINT
find >> $STATUS_FILE

# ---- STATUS
head -1 $STATUS_FILE | jq

