chromeos:
    browser:
      - chrome
    editor:
    draw:
      - chrome canvas
      - concepts
      - krita
    terminal:
      - linux development terminal
    camera:
      - chromeos camera
    screenshot:
      - Screen capture
    screencast:
      - screencast
    photo:
      - google photo [browse + edit]
      - gallery
    video:
    file-browser:
      - Files
    call:
      - zoom
      - google meet
    map:
      - google map


chrome-web-browser:
  extension:
    editor:
      - Code Pad Text Editor
      - text
    monitor:
      - cog - system info viewer
    adblock:
      - ublock origin
    remote-desktop:
      - chrome remote desktop
    draw:
  cloud-free:
      music:
        - soundcloud
        - spotfiy
        - youtube-music
      video:
        - youtube
      office:
        - google keep
        - google spreadsheet
        - google docs
        - google slide
        - google calendar
        - google drive
      call:
        - google meet
        - zoom
      map:
        - google map
      draw:
        - lucid chart
linux:
    editor:
      - vim
      - gvim
      - marktext.appImage
    terminal:
      - gnome-terminal
      - bash
    game:
      - warzone
    browser:
      - firefox
    draw:
      - gimp
      - inkscape
      - krita
      - blender
      - drawio.appImage

android:
    music:
      - spotify
    video:
      -
    call:
      - skype
      - team
    vpn:
      - nord-vpn
