#!/bin/bash
GRAPH_NAME=$1
NODE_NAME=$2
# ----
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
# ----
source .properd/VARSET
# ----
test -z "$GRAPH_NAME" && echo "GRAPH_NAME!" && exit 1

if test -z "$NODE_NAME" ; then
    CMD="GRAPH.DELETE $GRAPH_NAME"
else
    CMD="GRAPH.QUERY "$GRAPH_NAME" 'MATCH (n) WHERE ID(n) = "$NODE_NAME" DELETE n'"
fi
test -z "$AUTO_YES" || echo "Deleting ${GRAPH_NAME}[$NODE_NAME] in 10s" && sleep 10
echo $CMD | docker exec -i $CONTAINER_NAME redis-cli -h $REDIS_HOST -p $REDIS_PORT
