#!/bin/bash
GRAPH_NAME=$1
# ----
source .properd/VARSET
# ----
test -z "$GRAPH_NAME" && .function/list && read -p "GRAPH_NAME ?= " GRAPH_NAME
export OUTPUT_FORMAT=no-raw
echo "GRAPH.RO_QUERY ${GRAPH_NAME}  \"MATCH (a)-[r]->(b) RETURN r\"" | .function/cli

#|\
#        head -n -2   | tail -n +3 |\
#        awk '{if ($1 ~ "^[0-9]+") print $1" "; else  print $1"," }' |\
#        awk -F "\n" 'BEGIN {RS=",\n"; print "ID NAME"} {print $1  $2}'
