#!/bin/bash -x

IN_ADDR=$1
IN_PORT=$2
OUT_ADDR=$3
OUT_PORT=$4
PROTO=$5


test -r VARSET && source VARSET
    test -z "$IN_ADDR" && IN_ADDR=10.5.11.1
    test -z "$IN_PORT" && IN_PORT=139
    test -z "$OUT_ADDR" && OUT_ADDR=10.13.0.1
    test -z "$OUT_PORT" && OUT_PORT=1390
    test -z "$PROTO" && PROTO=tcp

sysctl -w net.ipv4.ip_forward=1

# NAT: modify delivery address
iptables -t nat -A PREROUTING \
    -p $PROTO --destination $IN_ADDR  --dport $IN_PORT \
    -j DNAT --to-destination $OUT_ADDR:$OUT_PORT

#iptables -F -t nat
