#!/bin/bash
CONTAINER_DIR=$1
# ----
source .properd/VARSET
test -n "$CONTAINER_DIR" && source $CONTAINER_DIR/.properd/VARSET
# ----

IMAGE=$(echo $DKR_IMAGE | awk -F ":" '{print $1}')
VERSION=$(echo $DKR_IMAGE | awk -F ":" '{print $2}')
DKR_IMAGE_FILE=$ARTEFACT_DIR/$IMAGE/$VERSION.tar.gz

ffunction artefacts

if test -f $DKR_IMAGE_FILE ; then
        echo "Loading in image in 10s" ; sleep 10
        sudo docker load < ${DKR_IMAGE_FILE}
fi

