#!/bin/bash 

OBJECTORY=$1

function docker_arti_get () {
    local app_varset=$1
    local objectory=$(dirname $(dirname $app_varset))
    cd $objectory
    if test -x .function/artefact-get ; then
          .function/artefact-get
    else
        source .properd/VARSET
        echo "-------- ARTIFACT: $DKR_IMAGE --------"
        local img_path=$(echo $ARTEFACT_DIR/$DKR_IMAGE | sed s,:,__,)
        mkdir -p $(dirname $img_path)
        docker pull $DKR_IMAGE
        docker save $DKR_IMAGE | gzip > $img_path
    fi
    cd -
}
if test -z "$OBJECTORY" ; then
    for app_varset in $(find apps | grep .properd/VARSET) ; do
        echo "log=== $app_varset"
        docker_arti_get $app_varset
    done
else
    docker_arti_get $OBJECTORY/.properd/VARSET
fi
