#!/bin/bash -xe

#DATUM_SHARED=[optional exported]
#ENV_FILE=[optional exported]
#DKR_IMAGE=[optional exported] 
#DKR_EXPOSE=[optional exported] 

test -z "$DKR_IMAGE" && DKR_IMAGE=fedora:32

if [[ "$1" =~ ^.function/ ]]; then
    # RUN A FUNCTION SCRIPT INSIDE CONTAINER
    FUNCTION_PATH=$(readlink -f $1)
    CONTEXT_DIR=$(dirname   $(echo $FUNCTION_PATH | grep -o "^.*.function"))
    RUN_ID=$(date -u '+%Y-%m-%dT%H-%M-%SZ')
    DATUM=.datum/${RUN_ID}
    test -z "$DATUM_SHARED" && DATUM_SHARED=${CONTEXT_DIR}/.datum/shared
    test -n "$DKR_EXPOSE" && PORT_PUBLISH="--publish $DKR_EXPOSE:$DKR_EXPOSE"
    test -n "$ENV_FILE" && ENV_FILE="--env-file $ENV_FILE"
    NEO=$1
    NEO_PARAMS=${*:2}
    mkdir -p $CONTEXT_DIR/$DATUM
    mkdir -p $DATUM_SHARED
    sudo docker run \
            --rm \
            --mount  type=bind,source=${CONTEXT_DIR},target=/matrix  \
            --mount  type=bind,source=${DATUM_SHARED},target=/datum_shared  \
            --env  RUN_ID=${RUN_ID} \
            --env  DATUM=/matrix/$DATUM \
            --env  DATUM_SHARED=/datum_shared \
            ${PORT_PUBLISH} \
            ${ENV_FILE} \
            $DKR_IMAGE \
            bash -c "cd matrix;   /matrix/$NEO $NEO_PARAMS " \
        2>&1 | tee  $CONTEXT_DIR/$DATUM/log.std
    echo "Runbox completed"
else
    CMD=$@
    [ "$1" == "bash" ] && STDIO="-i -t"
    sudo docker run ${STDIO} --rm  $DKR_IMAGE ${CMD}
fi
