#!/bin/bash

CONFIG_SET=$1
# ----
PROMETH=prometh
USER=prometheus
DKR_DNS=8.8.8.8
PUBLISH=9090
# ----
source .properd/VARSET
# ----
! test -d $DATA_DIR  &&
    mkdir -p  $DATA_DIR/{config,log,data} &&
    chmod 0777 $DATA_DIR

docker run --detach \
    --rm \
    --name $CONTAINER_NAME \
    --dns $DKR_DNS \
    --volume $PWD/$DATA_DIR/data:/$PROMETH/data \
    -p $PUBLISH:9090 \
    $DKR_IMAGE 
#    /opt/bitnami/prometheus/bin/prometheus \
#        --config.file=./prometheus.yml \
#        --storage.tsdb.path=${PROMETH}/data \
#        --web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries \
#        --web.console.templates=/opt/bitnami/prometheus/conf/consoles
#

