#!/bin/bash

PROMETH=prometh
USER=prometheus
useradd --shell /usr/sbin/nologin $USER
mkdir -p $PROMETH/data
chown -R $USER  $PROMETH

runuser -u $USER  -- \
    /opt/bitnami/prometheus/bin/prometheus \
        --config.file=./prometheus.yml \
        --storage.tsdb.path=${PROMETH}/data \
        --web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries \
        --web.console.templates=/opt/bitnami/prometheus/conf/consoles

