#!/bin/bash

OBJECTORY=$1

cd $OBJECTORY
mkdir -p .properd
mkdir -p .function
mkdir -p .template
mkdir -p .docs
mkdir -p datum

touch README.md
touch .properd/VARSET
touch .function/start  && chmod 0700 .function/start
touch .function/artefacts && chmod 0700 .function/artefacts
touch .function/artefact-get && chmod 0700 .function/artefact-get
test -f .properd/meta.yaml || echo "wid: $(uuidgen)" >  .properd/meta.yaml

# ---- TEMPlATE: .function/start
test -s .function/start || cat <<EOF  > .function/start
#!/usr/bin/env bash
#set -x
# ---- |EXT ----
VARSET_EXT=\$1
# ---- |DEFAULT ----

# ---- |OVERRIDE ----
source .properd/VARSET
test -n "\$VARSET_EXT" && source \$VARSET_EXT

# ---- |MAIN ----
EOF
