---
- hosts: kluster
  become: true
  tasks:
    - name: Remove swapfile from /etc/fstab | rid-yK1a
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
  
  
    - name: Disable swap | rid-vqHl
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
  
    - name: crio - registries | rid-ZZKo 
      template:
        src: templates/etc/containers/registries.conf
        dest: /etc/containers/registries.conf
        backup: yes
 
    - name: crio - restart | rid-2uJX
      service:
        name: crio
        daemon_reload: yes
        enabled: yes
        state: restarted
  
  
    - name: kubelet - node ip | rid-DFLM
      lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_eth1.ipv4.address }}
        create: yes
 
    - name: kernel module - config | rid-QFYZ 
      template:
        src: templates/etc/modules-load.d/k8s.conf
        dest: /etc/modules-load.d/k8s.conf
        backup: yes
        
    - name: kernel module - loading | rid-0ZN8
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter
  
    - name: sysctl - config | rid-hUPY 
      template:
        src: templates/etc/sysctl.d/k8s.conf
        dest: /etc/sysctl.d/k8s.conf
        backup: yes
  
    - name: sysctl - apply | rid-5q9o 
      command: sysctl --system
 
  
    - name: kubelet - restart | rid-pwv3
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted


- hosts: master
  become: true
  tasks:

  - name: kubeadm - init kluster | rid-iVAi
    command: kubeadm init  --cri-socket unix:///var/run/crio/crio.sock --apiserver-advertise-address="{{ ansible_eth1.ipv4.address }}" --apiserver-cert-extra-sans="{{ ansible_eth1.ipv4.address }}"  --pod-network-cidr=10.111.111.0/24 

  - name: kubeconfig - client setup for vagrant user | rid-WoOM
    command: "{{ item }}"
    with_items:
      - mkdir -p /home/vagrant/.kube
      - cp -b /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      - chown vagrant:vagrant /home/vagrant/.kube/config


  - name: kubeconfig - fetch from master node | rid-GMO5
    ansible.builtin.fetch:
      src: /etc/kubernetes/admin.conf
      dest: ~/.kube/config.vagrant_kluster
      flat: yes


  - name: calico - install network plugin | rid-NI2o 
    become: no
    command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/calico.yaml


  - name: First Node - ready check | rid-7no1
    become: no
    shell: |
      kubectl wait --for=condition=Ready nodes --selector kubernetes.io/hostname=$(hostname) --timeout=180s 
