---
- hosts: kluster
  become: true
  tasks:
  - name: apt - necessary packages | rid-As8g
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - jq

  - name: apt key - google repo | rid-oGFX
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: apt repo - kubernetes.io | rid-SR0E
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: os - get version
    shell: |
      source /etc/os-release
      echo $VERSION_ID
    args:
      executable: /bin/bash
    register: os_release

  - name: os - get version
    set_fact:
      os_version: "{{ os_release.stdout }}"


  - name: apt key - suse repo key | rid-LVlC
    apt_key:
      url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
      state: present


  - name: apt repo - suse repo | rid-SR0E
    apt_repository:
      repo: "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /"
      state: present
      filename: opensuse.devel.kubic.libcontainers.stable.list
      #update_cache: false

  - name: apt - podman | rid-XeUn
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - podman


  - name: apt - Install Kubernetes binaries | rid-oHFV
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl

  - name: crio - install container runtime | CRIO
    shell: |
      curl --retry 5 --retry-delay 3 https://raw.githubusercontent.com/cri-o/cri-o/main/scripts/get | bash




