---
- hosts: kluster
  become: true
  tasks:
  - name: Add vagrant user to docker group | rid-jBVv 
    user:
      name: vagrant
      group: docker
   

  - name: Remove swapfile from /etc/fstab | rid-yK1a
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none


  - name: Disable swap | rid-vqHl
    command: swapoff -a
    when: ansible_swaptotal_mb > 0


  - name: Docker dir create | rid-Bk8a
    ansible.builtin.file:
      path: /etc/docker
      state: directory
      mode: '0755'


  - name: Docker daemon config | rid-hXUo
    copy: src=config/docker/daemon.json dest=/etc/docker/daemon.json mode=0644


  - name: Restar Docker | rid-2uJX
    service:
      name: docker
      daemon_reload: yes
      state: restarted


  - name: Configure node ip | rid-DFLM
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_eth1.ipv4.address }}
      create: yes


  - name: Restart kubelet | rid-pwv3
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted




- hosts: master
  become: true
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm | rid-iVAi
    command: kubeadm init  --apiserver-advertise-address="{{ ansible_eth1.ipv4.address }}" --apiserver-cert-extra-sans="{{ ansible_eth1.ipv4.address }}"  --pod-network-cidr=10.111.111.0/24
 

  - name: Setup kubeconfig for vagrant user | rid-WoOM
    command: "{{ item }}"
    with_items:
      - mkdir -p /home/vagrant/.kube
      - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      - chown vagrant:vagrant /home/vagrant/.kube/config


  - name: Download client kube config | rid-GMO5
    ansible.builtin.fetch:
      src: /etc/kubernetes/admin.conf
      dest: ~/.kube/config.vagrant_kluster
      flat: yes


  - name: Network plugin Calico yaml | rid-H0oq
    become: no
    copy: src=plugins/calico/calico.yaml  dest=~/calico.yaml  mode=0644


  - name: Network plugin Calico | rid-Z6au
    become: no
    shell: |
      kubectl apply -f calico.yaml


  - name: First Node Ready | rid-7no1
    become: no
    shell: |
      kubectl wait --for=condition=Ready nodes --selector kubernetes.io/hostname=$(hostname) --timeout=180s 
