#!/bin/bash -x
source VARS
PACKAGE_DIR=$(readlink -f $WORKSPACE/dist/)
\
python3 -m pip uninstall $PACKAGE_NAME
python3 -m pip install  --no-index --find-links file://$PACKAGE_DIR  --user $PACKAGE_NAME==$PACKAGE_VERSION
