#!/bin/bash

GMLBASE=${GMLBASE:-~/.lmstudio/models}
PROPERD=~/echo-home/workstation/lmstudio/gmlama/.properd
GML_YSON=$PROPERD/gml.${HOSTNAME}.yson
cat $GML_YSON | grep --color -n '^.*:' && read -p "Model ID ?= " model_id
gml_line=$(sed -n ${model_id}p < $GML_YSON)
gml_describe=$(echo "$gml_line" | yq 'to_entries  | .[0].value[0]')
gml_params=$(echo "$gml_line" | yq 'to_entries  | .[0].value[1]')
gml_model=$(echo $gml_line | yq keys[])

if echo $gml_describe | grep -q '^GPU/' ; then
    set -x
    cd $LOCAL_BIN/gmlama-vulkan ; ./llama-cli -m $GMLBASE/$gml_model $gml_params
    exit 1   
fi
set -x
llama-cli -m $GMLBASE/$gml_model "$gml_params"
