#!/bin/bash

SELECTOR=$1
GMLBASE=${GMLBASE:-~/.lmstudio/models}
MODELS="
lmstudio-community/gemma-3-1B-it-QAT-GGUF/gemma-3-1B-it-QAT-Q4_0.gguf
lmstudio-community/LFM2.5-1.2B-Instruct-GGUF/LFM2.5-1.2B-Instruct-Q8_0.gguf
"

test -z "$SELECTOR" && echo -n "$MODELS" && exit 1

llm=$(echo -n "$MODELS" | grep -i -m 1 $SELECTOR)
llama-cli -m $GMLBASE/$llm
