#!/bin/bash
MODEL_ID=$1
GMLBASE=${GMLBASE:-~/.lmstudio/models}
PROPERD=~/echo-home/workstation/lmstudio/gmlama/.properd
GML_YSON=$PROPERD/gml.${HOSTNAME}.yson
GPU_TYPE=vulkan




if test -z "$MODEL_ID" ; then
  cat $GML_YSON | grep --color -n '^.*:' && read -p "MODEL_ID ?= " MODEL_ID
else
  if ! [[ "$MODEL_ID" =~ ^[0-9]+$ ]] ; then
    cat <<EOF
Usage: gml8w <model_ID>

Description:
  Run the gml8w command with a specific model ID.

Available Models:
$(cat $GML_YSON | grep --color -n '^.*:')

Examples:
  gml8w 1        # Run with model "1"
  gml8w 2        # Run with model "2"
EOF
    exit 1
  fi
fi



gml_line=$(sed -n ${MODEL_ID}p < $GML_YSON)
gml_describe=$(echo "$gml_line" | yq 'to_entries  | .[0].value[0]')
gml_params=$(echo "$gml_line" | yq 'to_entries  | .[0].value[1]' | envsubst | sed -E 's/([A-Z]):\\/\/\L\1\//g' | sed 's,\\,\/,g')
llamacpp_version=$(echo "$gml_line" | yq 'to_entries  | .[0].value[2]')
gml_dev=$(echo "$gml_line" | yq 'to_entries  | .[0].value[3]' | envsubst | sed -E 's/([A-Z]):\\/\/\L\1\//g' | sed 's,\\,\/,g')
gml_model=$(echo $gml_line | yq keys[])

test -n "$GML_DEV" && gpu_dev="-dev $GML_DEV"
if ! [[ "$gml_dev" =~ 'null' ]] ; then
    gpu_dev="-dev $gml_dev"
    GML_DEV=$gml_dev
fi
[[ "$llamacpp_version" =~ 'null' ]] && unset llamacpp_version
if echo $gml_describe | grep -q '^GPU/' ; then
    if gmlvk-dev | grep -i "  $GML_DEV: NVIDIA" ; then
        GPU_TYPE=CUDA
    fi
    set -x
    cd $LOCAL_BIN/gmlama-$GPU_TYPE/${llamacpp_version} ; ./llama-server -m $GMLBASE/$gml_model $gml_params $gpu_dev
    exit 1   
fi
set -x
cd $LOCAL_BIN/gmlama/${llamacpp_version} ; ./llama-server -m $GMLBASE/$gml_model $gml_params
