#!/bin/bash -x

LIST="
gml8
gml16
gml32
gml64
gml642
gml644
gml648
"

for cmd in $LIST; do
  ln -sf $(readlink -f .function/gmlx)  $LOCAL_BIN/gmlama/$cmd
  ln -sf $(readlink -f .function/gmlxvk)  $LOCAL_BIN/gmlama/${cmd}vk
done
