#!/usr/bin/env bash
#set -x
# ---- |EXT ----
VARSET_EXT=$1
# ---- |DEFAULT ----
export ENV_DATE=$(date +%Y)
export DATA_DIR=./datum/$ENV_DATE
# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----
COLUMNS="TODO  HOLD  WIP  DONE"
mkdir -p $DATA_DIR/${YEAR}/{TODO,HOLD,WIP,DONE}

test -n "$GVIMPATH" && G_VIM=g

${G_VIM}vim -u .vimrc
