#!/usr/bin/env bash
#set -x
# ---- |EXT ----
PROJECT_CODE=$1
VARSET_EXT=$2
# ---- |DEFAULT ----
export ENV_DATE=$(date +%Y)
export DATA_DIR=./datum/$ENV_DATE
# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----

# ---- project check
PROJECT_MD=$DATA_DIR/PROJECT.md
test -s $PROJECT_MD || cp .template/PROJECT.md $PROJECT_MD
source .template/project_row
cat $PROJECT_MD
test -z "$PROJECT_CODE" && read -p "PROJECT ?= " PROJECT_CODE
export PROJECT_CODE=$PROJECT_CODE
if ! grep -q "^$PROJECT_CODE :" $PROJECT_MD ; then
    echo "$PROJECT_CODE is new PROJECT_CODE"
    read -p "DESCRIPTION ?= " DESCRIPTION
    export DESCRIPTION=$DESCRIPTION
    export LAST_ID=-1
    sed -i '$d' $PROJECT_MD
        # sed delete last line
    echo $TEMPLATE_PROJECT_ROW | envsubst >> $PROJECT_MD
    echo '```' >> $PROJECT_MD
fi
LAST_ID=$(grep  "^$PROJECT_CODE :"  $PROJECT_MD  | grep -o '{.*}' | jq -r .last_id)
    # yson: get field
LAST_ID=$((LAST_ID + 1))
json=$(grep  "^$PROJECT_CODE :" $PROJECT_MD  | grep -o '{.*}' | jq -c ".last_id = $LAST_ID")
sed -i "s/^${PROJECT_CODE} :.*/$PROJECT_CODE : ${json}/" $PROJECT_MD
    # yson: update field
git add $PROJECT_MD


# ---- card generation
CARD=$DATA_DIR/TODO/${PROJECT_CODE}-${LAST_ID}.md
TEMPLATE_CARD=.template/${PROJECT_CODE}.CARD.md
test -s $TEMPLATE_CARD || TEMPLATE_CARD=CARD.md
cat $TEMPLATE_CARD | envsubst > $CARD
git add $CARD
echo -e "\nCARD=$CARD"
