#!/bin/bash



# ---- PACKAGE ----
sudo dnf update -y

sudo dnf install -y \
    git \
    telnet \
    python3-pip \
    jq \
    vim \
    vim-X11 \
    rsync \
    openssh-server

sudo pip3 install --no-cache-dir \
    yq

cp .bashrc.edit $HOME

