#!/usr/bin/env bash
#set -x
# ---- |EXT ----
# ---- |DEFAULT ----

# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----
pip install --force-reinstall $ARTIFACT_DIR/$REQUIREMENT/*.whl
