#!/usr/bin/env bash
#set -x
# ---- |EXT ----
# ---- |DEFAULT ----

# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----
mkdir -p $ARTIFACT_DIR/$REQUIREMENT
pip download -r .requirements/$REQUIREMENT -d $ARTIFACT_DIR/$REQUIREMENT
