#!/bin/bash -x 
NAME=${1:-all}
ARTIFACT_DIR=./artefacts
ARTIFACT_YSON=.properd/artefacts.yaml

function ready (){
	local name=$1
	local ARTIFACT_VERSION=$(cat $ARTIFACT_YSON | yq -r ".${name}[0]")
    

    test -r $ARTIFACT_DIR/.function/ready/$name && source $ARTIFACT_DIR/.function/ready/$name && return
    export UV_TOOL_DIR="./$name/uv-tools"
    export UV_TOOL_BIN_DIR="./$name/bin"
    uv tool install $name@v$ARTIFACT_VERSION
}

mkdir -p $ARTIFACT_DIR
if [[ "$NAME" =~ "all" ]] ; then
	LIST=$(cat $ARTIFACT_YSON | yq 'keys' | awk -F ' ' '{print $2}')
	for i in $LIST ; do
		ready $i
	done
	exit
fi
ready $NAME
