#!/bin/bash -x 
NAME=${1:-all}
ARTIFACT_DIR=./artefacts
ARTIFACT_YSON=.properd/artefacts.yaml

function ready (){
	local name=$1
	local ARTIFACT_VERSION=$(cat $ARTIFACT_YSON | yq -r ".${name}[0]")
	local IS_UV=$(cat $ARTIFACT_YSON | yq -r ".${name}[1].uv // false")

  test -r $ARTIFACT_DIR/.function/ready/$name && source $ARTIFACT_DIR/.function/ready/$name && return

	if [[ "$IS_UV" == "true" ]]; then
     tar xf $ARTIFACT_DIR/$name-$ARTIFACT_VERSION${OS}.tar.gz -C $ARTIFACT_DIR
     ln -sf $(readlink -f $ARTIFACT_DIR/$name/bin/*) $LOCAL_BIN/$name
		 return
	fi

	# Handle pip package
	local PYTHON_VERSION=$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
	local TARGET_DIR="$LOCAL_BIN/python/$PYTHON_VERSION/$name"
	mkdir -p "$TARGET_DIR"
	
	# Find whl files in the artifact directory for this package
	find "$ARTIFACT_DIR/$name" -name "*.whl" | xargs pip install --target "$TARGET_DIR"


}

mkdir -p $ARTIFACT_DIR
if [[ "$NAME" =~ "all" ]] ; then
	LIST=$(cat $ARTIFACT_YSON | yq 'keys' | awk -F ' ' '{print $2}')
	for i in $LIST ; do
		ready $i
	done
	exit
fi
ready $NAME
