#!/bin/bash


# $@ with escaping preserves exact arguments and internal quotes
CMD=""
for arg in "$@"; do
  CMD="$CMD $(printf '%q' "$arg")"
done


osascript <<EOF
tell application "Terminal"
    set newTab to do script ""
    do script "$CMD" in newTab
end tell
EOF
