apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: crb--system--aggregate-to-view

roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:aggregate-to-view

subjects:
    - kind: ServiceAccount
      name: ureadonly
      namespace: kdash
