#!/usr/bin/env bash
#set -x
# ---- |EXT ----
VARSET_EXT=$1
# ---- |DEFAULT ----

# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----
export OPENAI_API_BASE="http://localhost:8080/v1"
export OPENAI_API_KEY="localm"
export AIDER_MODEL=openai/$(curl -s http:/localhost:8080/models | jq .models[0].name)

#aider --openai-api-base http://localhost:8080/v1 --openai-api-key localm --model $(curl http:/localhost:8080/models | jq .models[0].name)
aider  --no-gitignore --no-show-model-warnings
