#!/bin/bash

SSH_HOST=$1
SUB_DIR=$2
VARSET_EXT=$3
# ----
test -z "$SSH_HOST" && echo "SSH_HOST!" && exit 1
test -z "$SUB_DIR" && SUB_DIR='~'
test -n "$VARSET_EXT" && source $VARSET_EXT
# ----
export SSH_HOST=$SSH_HOST
export SUB_DIR=$SUB_DIR
export WORKDIR=$(basename $SUB_DIR)

vim -u ~/.vim/rc/artillery
