#!/bin/bash

source .properd/VARSET

ansible-playbook  -vvv \
    -i ./inventory  \
    --extra-vars "ARTEFACT_DIR=$ARTEFACT_DIR" \
    --extra-vars "@.properd/VARSET.yaml" \
    books/play_artefact_get.yaml


