#!/usr/bin/env bash
#set -x
# ---- |EXT ----
VARSET_EXT=$1
# ---- |DEFAULT ----

# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----
#!/bin/bash

sudo apt update
sudo apt install -y $APT_LIST

