#!/bin/bash

SRC_KEYSTORE=$1
DEST_KEYSTORE=$2
read -p "SRC: Enter passphrase to unlock $SRC_KEYSTORE : " SRC_PASSPHRASE_KEYSTORE
read -p "DEST: Enter passphrase to unlock $DEST_KEYSTORE : " DEST_PASSPHRASE_KEYSTORE

# ---- SOURCE KEYSTORE ----
SRC_KEYSTORE_PRINT="$(keytool -list -v -keystore $SRC_KEYSTORE -storepass $SRC_PASSPHRASE_KEYSTORE 2>/dev/null)"
SRC_KEYSTORE_TYPE=$(echo $SRC_KEYSTORE_PRINT | grep -o "Keystore type: [^ ]\+" | awk -F":" '{print $2}')
echo "---- LIST ENTRY: $SRC_KEYSTORE ----"
echo $SRC_KEYSTORE_PRINT | grep -o "Alias name: [^ ]\+"
read -p "SRC_ALIAS_NAME ? = " SRC_ALIAS_NAME


# ---- DESTINATION KEYSTORE ----
DEST_KEYSTORE_PRINT="$(keytool -list -v -keystore $DEST_KEYSTORE -storepass $DEST_PASSPHRASE_KEYSTORE 2>/dev/null)"
DEST_KEYSTORE_TYPE=$(echo $DEST_KEYSTORE_PRINT | grep -o "Keystore type: [^ ]\+" | awk -F":" '{print $2}')
echo "---- LIST ENTRY: $DEST_KEYSTORE ----"
echo $DEST_KEYSTORE_PRINT | grep -o "Alias name: [^ ]\+"
read -p "DEST_ALIAS_NAME ? = (can set new name) " DEST_ALIAS_NAME



echo -e " \n\n---- ADDING ENTRY ----"
keytool  -importkeystore   \
    -srckeystore $SRC_KEYSTORE \
        -srcstorepass $SRC_PASSPHRASE_KEYSTORE \
        -srcalias $SRC_ALIAS_NAME \
        -srcstoretype $SRC_KEYSTORE_TYPE \
    -destkeystore $DEST_KEYSTORE \
        -deststorepass $DEST_PASSPHRASE_KEYSTORE \
        -destalias $DEST_ALIAS_NAME  \
        -deststoretype $DEST_KEYSTORE_TYPE    2>/dev/null

echo "Keystore Entries"
keytool -list -keystore $DEST_KEYSTORE -storepass $DEST_PASSPHRASE_KEYSTORE 2>/dev/null



