#!/bin/bash
#
#
NAMESPACE=$1
SERVICEACCOUNT=$2
source .function/varcheck-NAMESPACE
source .function/varcheck-SERVICEACCOUNT


kubectl  get secret -n $NAMESPACE -o json | \
    jq -r ".items[] 
        | select(.type==\"kubernetes.io/service-account-token\")
        | select(.metadata.annotations.\"kubernetes.io/service-account.name\"==\"$SERVICEACCOUNT\") 
        | \"\\n\\n\" + .metadata.name + \"  :  \" + .data.token
       "


