#!/bin/bash

ARTEFACT_DIR=${ARTEFACT_DIR:-artefacts}
mkdir -p $ARTEFACT_DIR

set -x
curl -Lo $ARTEFACT_DIR/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  && chmod +x $ARTEFACT_DIR/minikube

