#!/bin/bash

#VARSET_FILE=$1
# ----
VAULT_ADDR='http://127.0.0.1:8200'
VAULT_TOKEN=$(<datum/token)
PUBLISH=8200
CONFIG_DIR=config
DATA_DIR=datum

# ----
source .properd/VARSET
# ----


docker exec \
    --env VAULT_ADDR=$VAULT_ADDR \
    --env VAULT_TOKEN=$VAULT_TOKEN \
    $CONTAINER_NAME  vault $@

    #--detach \
