#!/bin/bash

VARSET_FILE=$1
# ----
VAULT_ADDR='http://127.0.0.1:8200'
export VAULT_TOKEN="hvs.6j4cuewowBGit65rheNoceI7"
# ----
source .properd/VARSET

vault server \
    -config=$CONFIG_DIR/server.hcl

