#!/bin/bash
source .function/pgbase

FILE_PATH=$1

gpg2  --list-keys --keyid-format short
read -p "Key Fingerprint ?=  " KEY_FINGERPRINT

if test -n "$KEY_FINGERPRINT" ; then
    gpg2  --recipient ${KEY_FINGERPRINT}  --encrypt ${FILE_PATH}
    echo "ENCRYPTED: ${FILE_PATH}.gpg"
else
    echo "Please select Key Fingerprint"
fi
