#!/bin/bash
source .function/pgbase

gpg2  --list-secret-keys --keyid-format short
read -p "Key Fingerprint ?=  " KEY_FINGERPRINT

if test -n "$KEY_FINGERPRINT" ; then
    recipient=$(gpg2  --list-secret-keys $KEY_FINGERPRINT | grep -o "[^ <>]\+@[^ >?]\+" | sed 's/\@/_at_/')
    file_name=pgp-sec-${recipient}-${KEY_FINGERPRINT:0:8}.asc
    gpg2 --armor --export-secret-keys ${KEY_FINGERPRINT} > ./${file_name}
    echo "Exported: ${file_name}"
else
    echo "Please select Key Fingerprint"
fi
