apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{PREFIX}}-volume-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/{{PREFIX}}/0"
