persistence:
  enabled: true
  size: 10Gi
  storageClass: manual
  replicaCount: 2
  existingClaim: "{{PREFIX}}-pvc"
ingress:
  enabled: true
  hosts: ["{{PREFIX}}.registry"]
  tls:
    - secretName: "{{PREFIX}}-tls"
      hosts: ["{{PREFIX}}.registry"]
  annotations:
    kubernetes.io/ingress.class: "nginx"
podLabels:
  type: local


