#!/bin/bash -x

VERSION=1.0.3
TF_PATH=~/.local/bin/terraform-${VERSION}
curl -s  https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_amd64.zip \
    | funzip > $TF_PATH 

chmod 0700 $TF_PATH

ln -sf $TF_PATH $(dirname $TF_PATH)/terraform
