#!/bin/bash -x

NAME=$1
TYPE=$2
CONSUL_DNS_LOOKUP_TYPE=$(echo $NAME | awk -F "." '{print $NF}')
NAME=${NAME%.*}
    #bash: remove file extension
test -z "$TYPE" && TYPE=ANY
# ----
source .properd/VARSET
source .properd/VARSET.client

# ----
NAME_FULL=${NAME}.${CONSUL_DNS_LOOKUP_TYPE}.${DATACENTER}.consul
test -z "$CONSUL_DNS_LOOKUP_TYPE" && CONSUL_DNS_LOOKUP_TYPE=service
dig @$ADDRESS_DNS -p 8600   $NAME_FULL  $TYPE
