#!/usr/bin/env bash
source .properd/VARSET


WORKDIR="datum"
ASSETS="${WORKDIR}/assets"
# LOGS="${WORKDIR}logs/"

mkdir -p ${ASSETS}

export DATACENTER=${DATACENTER:-"dc1"}
export DOMAIN=${DOMAIN:-"consul"}
export CONSUL_DATA_DIR=${CONSUL_DATA_DIR:-"/etc/consul/data"}
export CONSUL_CONFIG_DIR=${CONSUL_CONFIG_DIR:-"/etc/consul/config"}

export CONSUL_HTTP_ADDR="http://127.0.0.1:8500"
export CONSUL_HTTP_SSL=false
export CONSUL_CACERT="${CONSUL_CONFIG_DIR}/consul-agent-ca.pem"
export CONSUL_TLS_SERVER_NAME="server.${DATACENTER}.${DOMAIN}"
export CONSUL_FQDN_ADDR="consul${FQDN_SUFFIX}"

export CONSUL_HTTP_TOKEN=`cat .properd/token.bootstrap | jq -r ".SecretID"`

echo "Create ACL policies and tokens"
cat .template/acl-policy-dns.hcl | envsubst > ${ASSETS}/acl-policy-dns.hcl
cat .template/acl-policy-server-node.hcl | envsubst >  ${ASSETS}/acl-policy-server-node.hcl

consul acl policy create -name 'acl-policy-dns' -description 'Policy for DNS endpoints' -rules @${ASSETS}/acl-policy-dns.hcl
consul acl policy create -name 'acl-policy-server-node' -description 'Policy for Server nodes' -rules @${ASSETS}/acl-policy-server-node.hcl
consul acl token create -description 'DNS - Default token' -policy-name acl-policy-dns --format json > ${ASSETS}/acl-token-dns.json

DNS_TOK=`cat ${ASSETS}/acl-token-dns.json | jq -r ".SecretID"`

## Create one agent token per server
echo "Setup ACL tokens for Server"

consul acl token create -description "server agent token" -policy-name acl-policy-server-node  --format json > ${ASSETS}/server-acl-token.json

SERV_TOK=`cat ${ASSETS}/server-acl-token.json | jq -r ".SecretID"`

consul acl set-agent-token agent ${SERV_TOK}
consul acl set-agent-token default ${DNS_TOK}
