#!/bin/bash -x

VARSET_FILE=$1
# ----
MODE=client
export DATACENTER=dc1
export DOMAIN=consul
CONSUL_DATA_DIR=./datum/$MODE
export CONSUL_CONFIG_DIR=./config/$MODE
CLUSTER_ADDR=127.0.0.1
CLUSTER_PORT=8311
BIND_ADDR=127.0.0.1
export ADDRESS_GRPC=127.0.0.1
export ADDRESS_HTTP=127.0.0.1
export ADDRESS_DNS=127.0.0.1

# ----
source .properd/VARSET
source .properd/VARSET.$MODE
test -n "$VARSET_FILE" && source $VARSET_FILE
# ----
export AGENT_TOKEN=$(cat $AGENT_TOKEN_FILE | jq -r .SecretID)
cat $CONSUL_CONFIG_DIR/agent.hcl.template | envsubst > $CONSUL_CONFIG_DIR/agent.hcl
consul validate ${CONSUL_CONFIG_DIR}
consul agent \
    -ui \
    -node=${HOSTNAME}-$MODE \
    -datacenter=${DATACENTER} \
    -config-dir=${CONSUL_CONFIG_DIR} \
    -bind=${BIND_ADDR} \
    -join=${CLUSTER_ADDR}:${CLUSTER_PORT} \
    -rejoin \
    -data-dir=${CONSUL_DATA_DIR}
