#!/bin/bash -x
VARSET_FILE=$1
# ----
MODE=server
export DATACENTER=vector
export DOMAIN=consul
CONSUL_DATA_DIR=./datum/$MODE
export CONSUL_CONFIG_DIR=./config/$MODE
export DNS_RECURSOR=1.1.1.1
export HTTPS_PORT=8443
export DNS_PORT=8600
export CONSUL_TLS_SERVER_NAME=server.$DATACENTER
export ADDRESS_GRPC=127.0.0.1
export ADDRESS_HTTP=127.0.0.1
export ADDRESS_HTTPS=127.0.0.1
export ADDRESS_DNS=127.0.0.1
BIND_ADDR=127.0.0.1
CLUSTER_ADDR=$BIND_ADDR
# ----
source .properd/VARSET
source .properd/VARSET.$MODE
test -n "$VARSET_FILE" && source $VARSET_FILE
# ----
PSTREE_ID=$(<.properd/pstree_id)
pstree -s -p $PSTREE_ID | grep -q consul && echo "PSTREE_ID=$PSTREE_ID alive" &&  exit 0
echo $$ > .properd/pstree_id

cat $CONSUL_CONFIG_DIR/agent.hcl.template | envsubst > $CONSUL_CONFIG_DIR/agent.hcl
consul validate ${CONSUL_CONFIG_DIR}
consul agent \
    -server \
    -bootstrap-expect=1 \
    -ui \
    -datacenter=${DATACENTER} \
    -node=${HOSTNAME} \
    -config-dir=${CONSUL_CONFIG_DIR} \
    -bind=${BIND_ADDR} \
    -data-dir=${CONSUL_DATA_DIR}
