apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole


metadata:
    name: argocd

rules:
    - apiGroups: [""]
      resources: [""]
      verbs:
        - create
        - delete
        - update
        - get
        - list
        - watch
