#!/bin/bash -e

SET=${1:-base}
RELEASE=$(cat /etc/redhat-release  | grep -o '[0-9]\+')
ARTEFACT_DIR=artefacts/$RELEASE/$SET
CHECKSUM=.properd/artefact.sha256sum/$RELEASE/$SET

cd $ARTEFACT_DIR
sudo dnf install --allowerasing --skip-broken *.rpm
