#!/bin/bash -x

MODE=server
NOMAD_DATA_DIR=./datum/$MODE
NOMAD_CONFIG_DIR=./config/$MODE
CLUSTER_ADDR=127.0.0.1
# ----
source .properd/VARSET
source .properd/VARSET.$MODE
# ----
mkdir -p $NOMAD_DATA_DIR
mkdir -p $NOMAD_DATA_DIR/plugins

export CONSUL_BOOTSTRAP_TOKEN=$(cat $CONSUL_BOOTSTRAP_TOKEN_FILE | jq -r .SecretID)
cat $NOMAD_CONFIG_DIR/agent.hcl.template | envsubst > $NOMAD_CONFIG_DIR/agent.hcl
nomad agent \
    -config=${NOMAD_CONFIG_DIR}/agent.hcl \
    -bind=${CLUSTER_ADDR} \
    -log-level INFO \
    -data-dir=$(readlink -f $NOMAD_DATA_DIR)
