#!/bin/bash -x
VARSET_FILE=$1
# ----
MODE=client
NOMAD_CONFIG_DIR=./config/$MODE
export NOMAD_DATA_DIR=$(readlink -f ./datum/$MODE)
BIND_ADDR=127.0.0.1
export CONSUL_ADDRESS=127.0.0.1:8500
export ADDRESS_HTTP=127.0.0.1
export ADDRESS_RPC=127.0.0.1
export ADDRESS_SERF=127.0.0.1
export PORT_HTTP=4646
export PORT_RPC=4647
export PORT_SERF=4648
export ADVERTISE_HTTP=127.0.0.1:$PORT_HTTP
export ADVERTISE_RPC=127.0.0.1:$PORT_RPC
export ADVERTISE_SERF=127.0.0.1:$PORT_SERF

# ----

source .properd/VARSET
source .properd/VARSET.$MODE
test -n "$VARSET_FILE" && source $VARSET_FILE

# ----
PSTREE_ID=$(<.properd/pstree_id.client)
pstree -s -p $PSTREE_ID | grep -q nomad && echo "PSTREE_ID=$PSTREE_ID alive" &&  exit 0
echo $$ > .properd/pstree_id.client

mkdir -p $NOMAD_DATA_DIR
mkdir -p $NOMAD_DATA_DIR/plugins
mkdir -p $NOMAD_DATA_DIR/volume_host
chmod 0777 $NOMAD_DATA_DIR/volume_host
export CONSUL_AGENT_TOKEN=$(cat $CONSUL_AGENT_TOKEN_FILE | jq -r .SecretID)
cat $NOMAD_CONFIG_DIR/agent.hcl.template | envsubst > $NOMAD_CONFIG_DIR/agent.hcl

sudo nomad agent \
    -config=${NOMAD_CONFIG_DIR}/agent.hcl \
    -bind=${BIND_ADDR} \
    -log-level INFO \
    -data-dir=$(readlink -f $NOMAD_DATA_DIR)
