#!/bin/bash

MODE=client
NOMAD_CONFIG_DIR=./config/$MODE
NOMAD_DATA_DIR=./datum/$MODE
CLUSTER_ADDR=127.0.0.1
# ----
source .properd/VARSET
source .properd/VARSET.$MODE

# ----
mkdir -p $DATA_DIR
mkdir -p $DATA_DIR/plugins
export CONSUL_BOOTSTRAP_TOKEN=$(cat $CONSUL_BOOTSTRAP_TOKEN_FILE | jq -r .SecretID)
cat $NOMAD_CONFIG_DIR/agent.hcl.template | envsubst > $NOMAD_CONFIG_DIR/agent.hcl

sudo nomad agent \
    -config=${NOMAD_CONFIG_DIR}/agent.hcl \
    -bind=${CLUSTER_ADDR} \
    -log-level INFO \
    -data-dir=$(readlink -f $NOMAD_DATA_DIR)
