#!/bin/bash

VALUES_FILE=$1


RELEASE=$(cat $VALUES_FILE |  yq ._helm_.release)
CHART=$(cat $VALUES_FILE |  yq ._helm_.chart)
CHART_VERSION=$(cat $VALUES_FILE |  yq ._helm_.chart_version)
CHART_LOCAL=$(cat $VALUES_FILE |  yq ._helm_.chart_local)
NAMESPACE=$(cat $VALUES_FILE |  yq ._helm_.namespace)


set -x
if [[ "$CHART_LOCAL" =~ "yes" ]]; then
  CHART=$(dirname $VALUES_FILE)
  helm upgrade --install $RELEASE $CHART -n $NAMESPACE --create-namespace -f $VALUES_FILE
else
  helm upgrade --install $RELEASE $CHART --version $CHART_VERSION -n $NAMESPACE --create-namespace -f $VALUES_FILE
fi
