#!/bin/bash

VALUES_FILE=$1


RELEASE=$(cat $VALUES_FILE |  yq ._helm_.release)
CHART=$(cat $VALUES_FILE |  yq ._helm_.chart)
CHART_VERSION=$(cat $VALUES_FILE |  yq ._helm_.chart_version)
CHART_LOCAL=$(cat $VALUES_FILE |  yq ._helm_.chart_local)
NAMESPACE=$(cat $VALUES_FILE |  yq ._helm_.namespace)

set -x
cd charts
helm pull $CHART --version $CHART_VERSION && tar xzf $(basename $CHART)-$CHART_VERSION.tgz
