#!/bin/bash -x
source .function/smb
USER=$1
test -z "$USER" && USER=root
export USER=$USER


if test -d /matrix ; then
    .function/setup
    SMB_OPTION="--foreground  --log-stdout"
    export WINDOWS=/matrix/$WINDOWS
    export SHADE=/matrix/$SHADE
fi


mkdir -p $WINDOWS $SHADE $SMBASE
chown -R $USER:$USER $WINDOWS
chown -R $USER:$USER $SHADE
chown -R $USER:$USER $SMBASE
chown -R $USER:$USER /var/log/samba
chown -R $USER:$USER /run/samba


runuser -u $USER -- \
    /usr/sbin/smbd  --configfile=${CONFIGFILE}  $SMB_OPTION

