#!/bin/bash

IP=$1
test -z "$IP" && IP=10.13.0.101
NAMESPACE=ingress-nginx
SERVICE=ingx-nginx-ingress
NODEPORT=$( kubectl get service $SERVICE -n $NAMESPACE -o json | jq .spec.ports[1].nodePort )


echo "---- INGRESS PATHS ----"
kubectl get ingress -A -o json \
    | jq  ' .items[] | select( .spec.ingressClassName == "nginx") | "\(.spec.rules[].host)\(.spec.rules[].http.paths[].path)"'
        # jq: select field value and return concatenated corresponding fields
        # output: HOST/SUBPATH

read -p "INGRESS_PATH ? = " INGRESS_PATH
HTTP_HOST=$(echo $INGRESS_PATH | awk -F '/'  '{print $1}')
SUBPATH=$(echo $INGRESS_PATH |grep -o  '/.*')
    # extract subpath exclude top folder



echo -e "\n---- RESPONSE ----"
curl -I -L -k --resolve $HTTP_HOST:$NODEPORT:$IP https://$HTTP_HOST:$NODEPORT/$SUBPATH
