#!/bin/bash -e
META_DIR_SHORT=.cache/meta
VOLUME_CACHE_SHORT=${PEDRIVE_VOLUME:-.cache/volume}
PEDRIVE_EXTENTS=${PEDRIVE_EXTENTS:-.properd/extents.yaml}
mkdir -p $META_DIR_SHORT
mkdir -p $VOLUME_CACHE_SHORT
export META_DIR=$(readlink -f $META_DIR_SHORT)
VOLUME_CACHE=$(readlink -f $VOLUME_CACHE_SHORT)
export LIST_EXTENTS=$(cat $PEDRIVE_EXTENTS | awk -F":" '{print $1}')


function abort(){
    local msg=$1
    echo $msg
    exit 1
}

function list_extents () {
  cat .properd/ntfs | awk -F "=" '{print $1}'
  return
}
