#!/bin/bash  

VOLUME_CACHE=$1
SUBPATH=$2
PFI_ID=${3:-PFI_ID__}

echo "Building manifest H256"
cd $VOLUME_CACHE
mkdir -p $SUBPATH/.properd
find  $SUBPATH -type f | xargs -I {} sha256sum {} > $SUBPATH/.properd/manifest.yaml

if [[ "$OS" =~ "Windows_NT" ]] ; then
  sed -i \
    -e "s/ \*/: {\"pfi\":[\"$PFI_ID\//" \
    -e 's/$/"]}/' \
    $SUBPATH/.properd/manifest.yaml
else
  sed -i \
    -e "s/  /: {\"pfi\":[\"$PFI_ID\//" \
    -e 's/$/"]}/' \
    $SUBPATH/.properd/manifest.yaml
fi

cd -
