#!/bin/bash

source .function/extents
source .properd/ntfs

SUB_PATH=$1
SUB_PATH_BUNDLE=$(  echo ${SUB_PATH}| sed s,/$,,  ).tar.xz
pedrive_bundle=$(cat $VOLUME_CACHE/$SUB_PATH/.properd/pedrive.yaml | yq '.bundle')
pedrive_encrypt_id=$(cat $VOLUME_CACHE/$SUB_PATH/.properd/pedrive.yaml | yq -r '.encrypt')
[[ $pedrive_bundle != "true" ]] && abort "FAILED AS BUNDLE MODE DISABLED [ $SUB_PATH/.properd/pedrive.yaml ]"

echo "Writing in bundle mode"
echo "$(date -u '+%Y-%m-%dT%H-%M-%SZ')  $HOSTNAME" >> $VOLUME_CACHE/$SUB_PATH/.properd/changelog
cd $VOLUME_CACHE/$(dirname $SUB_PATH)
tar cJf   $(basename $SUB_PATH_BUNDLE)   $(basename $SUB_PATH)
if [[ "$pedrive_encrypt_id"  =~  [A-Z0-9]+ ]] ; then
    echo "Encrypting with key $pedrive_encrypt_id"
    gpg2  --encrypt --recipient ${pedrive_encrypt_id}  --trust-model always --yes  $(basename $SUB_PATH_BUNDLE) || exit 1
    SUB_PATH_BUNDLE=${SUB_PATH_BUNDLE}.gpg
fi
cd -

#EXTENT=$(grep -l  $SUB_PATH_BUNDLE $META_DIR/*  | awk -F '/' '{print $NF}'  2>/dev/null)
EXTENT=$(ls $META_DIR/*  | awk -F '/' '{print $NF}'  2>/dev/null)
test -z "$EXTENT" && EXTENT=$(.function/pick-random-extent.py)
for ext in $EXTENT; do
  EXTENT_MOUNT=${!ext}
  test -r $EXTENT_MOUNT/.pedrive || continue
  mkdir -p $(dirname $VOLUME_CACHE/$SUB_PATH_BUNDLE)
  mkdir -p ${EXTENT_MOUNT}/"$(dirname $SUB_PATH_BUNDLE)"
  cp  $VOLUME_CACHE/$SUB_PATH_BUNDLE  ${EXTENT_MOUNT}/"$(dirname $SUB_PATH_BUNDLE)"
  cd $EXTENT_MOUNT && find 2>/dev/null > $META_DIR/$ext && cd -
  echo "[$ext] write"
done

echo "SUBPATH UPATED <<" 
echo $SUB_PATH_BUNDLE
rm $VOLUME_CACHE/$SUB_PATH_BUNDLE
