#!/bin/bash

source .function/extents
source .properd/ntfs

SUB_PATH=$1
if test -d $VOLUME_CACHE/$SUB_PATH ; then
    .function/write-bundle $SUB_PATH
    exit $?
fi
if ! test -f $VOLUME_CACHE/$SUB_PATH; then
    echo "Subpath must be file!"
    exit 1
fi

EXTENT=$(basename $(grep -l  $SUB_PATH $META_DIR/*  | head -1)  2>/dev/null)
test -z "$EXTENT" && EXTENT=$(.function/pick-random-extent.py)
EXTENT_MOUNT=${!EXTENT}

mkdir -p $(dirname $VOLUME_CACHE/$SUB_PATH)
mkdir -p ${EXTENT_MOUNT}/"$(dirname $SUB_PATH_BUNDLE)"
cp $VOLUME_CACHE/$SUB_PATH   ${EXTENT_MOUNT}/"$(dirname $SUB_PATH)"
cd $EXTENT_MOUNT && find  > $META_DIR/$EXTENT && cd -


echo "SUBPATH UPATED <<" 
echo $SUB_PATH
