#!/bin/bash

PASSWORD=${1:-$(openssl rand --base64 16)}
# ----
source .properd/VARSET
# ----
echo -n "$PASSWORD   #   " >&2
docker run --rm  $DKR_IMAGE    authelia crypto hash generate argon2 --password "$PASSWORD" | awk -F ": " '{print $2}' ||
    docker exec $CONTAINER_NAME    authelia crypto hash generate argon2 --password "$PASSWORD" | awk -F ": " '{print $2}'
