#!/bin/bash -x
source .properd/VARSET
NAME=$1
VERSION=$(yq -r ".${NAME}[0]" .properd/artefacts.yaml)
cd "$ARTIFACT_DIR"
tar --sort=name \
    --mtime="2026-01-01 00:00Z" \
    --owner=0 --group=0 --numeric-owner \
    -cf - "$NAME" | gzip -n > "${NAME}-${VERSION}${OS}.tar.gz"
