#!/bin/bash -x 
NAME=${1:-all}
ARTIFACT_DIR=./artefacts
ARTIFACT_YSON=.properd/artefacts.yaml

function install (){
    local name=$1
    local VERSION=$(cat $ARTIFACT_YSON | yq -r ".\"${name}\"[0]")
    
    mkdir -p "$ARTIFACT_DIR/$name"
    echo "Downloading npm package: $name@$VERSION"
    
    # npm pack downloads the tarball for the specific version
    npm pack "$name@$VERSION" --pack-destination "$ARTIFACT_DIR/$name"
}

mkdir -p $ARTIFACT_DIR
if [[ "$NAME" =~ "all" ]] ; then
    LIST=$(cat $ARTIFACT_YSON | yq 'keys' | awk -F ' ' '{print $2}')
    for i in $LIST ; do
        install $i
    done
    exit
fi
install $NAME
