#!/bin/bash -x 
NAME=${1:-all}
ARTIFACT_DIR=./artefacts
ARTIFACT_YSON=.properd/artefacts.yaml

function install (){
    local name=$1
    local VERSION=$(cat $ARTIFACT_YSON | yq -r ".\"${name}\"[0]")

    npm pack "$name@$VERSION" --pack-destination "$ARTIFACT_DIR/"
}

mkdir -p $ARTIFACT_DIR
if [[ "$NAME" =~ "all" ]] ; then
    LIST=$(cat $ARTIFACT_YSON | yq 'keys' | awk -F ' ' '{print $2}')
    for i in $LIST ; do
        install $(echo $i | tr -d "\r")
    done
    exit
fi
install $NAME
