#!/bin/bash -x 
NAME=${1:-all}
ARTIFACT_DIR=./artefacts
ARTIFACT_YSON=.properd/artefacts.yaml

function install (){
    local name=$1
    local VERSION=$(cat $ARTIFACT_YSON | yq -r ".\"${name}\"[0]")
    local TARGET_DIR="$ARTIFACT_DIR/$name"

    # Handle scoped packages by creating the scope directory
    if [[ "$name" == *"/"* ]]; then
        local scope=$(echo "$name" | cut -d'/' -f1)
        mkdir -p "$ARTIFACT_DIR/$scope"
        TARGET_DIR="$ARTIFACT_DIR/$scope/$name"
    fi

    # Ensure the specific target directory exists
    mkdir -p "$TARGET_DIR"

    npm pack "$name@$VERSION" --pack-destination "$ARTIFACT_DIR/"
}

mkdir -p $ARTIFACT_DIR
if [[ "$NAME" =~ "all" ]] ; then
    LIST=$(cat $ARTIFACT_YSON | yq 'keys' | awk -F ' ' '{print $2}')
    for i in $LIST ; do
        install $(echo $i | tr -d "\r")
    done
    exit
fi
install $NAME
