apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  namespace: ${NAMESPACE}
  name: token-${SERVICEACCOUNT}${TOKEN_NAME_SUFFIX}
  annotations:
    kubernetes.io/service-account.name: ${SERVICEACCOUNT}
