#!/bin/bash -e
META_DIR_SHORT=.cache/meta
VOLUME_CACHE_SHORT=.cache/volume
test -n "$PEDRIVE_VOLUME" && VOLUME_CACHE_SHORT=$PEDRIVE_VOLUME
mkdir -p $META_DIR_SHORT
mkdir -p $VOLUME_CACHE_SHORT
export META_DIR=$(readlink -f $META_DIR_SHORT)
VOLUME_CACHE=$(readlink -f $VOLUME_CACHE_SHORT)
export LIST_EXTENTS='
  DATUM_A001
  DATUM_B002
  DATUM_C003
'

powershell 'Get-Volume | Where-Object FileSystem -eq 'NTFS' | Select-Object DriveLetter, FileSystemLabel' | grep  'DATUM_[A-Z0-9]\{4\}'
