cluster = {
    "1" => { :cpus => 1, :mem => 2048 },
    "2" => { :cpus => 1, :mem => 2048 },
    "3" => { :cpus => 1, :mem => 2048 },
    "4" => { :cpus => 1, :mem => 1024 },
    "5" => { :cpus => 2, :mem => 3048 },
}


Vagrant.configure("2") do |config|
    cluster.each do |key,value|
        config.vm.define "vms#{key}" do |vmdef|
            vmdef.vm.box = "generic/ubuntu1804"
            vmdef.vm.hostname = "vagrant-s#{key}"
            vmdef.vm.network :private_network, :ip => "10.13.0.10#{key}"
            vmdef.vm.network :public_network, :dev => "virbr0", :mode => "bridge", :type => "bridge"
            vmdef.vm.synced_folder "../vagra", "/matrix" , type: "nfs" , nfs_udp: false
            vmdef.vm.provider :libvirt do |domain|
                domain.memory = value[:mem]
                domain.cpus = value[:cpus]
                domain.nested = true
                domain.disk_driver :cache => 'none'
                domain.qemu_use_session = false
                domain.management_network_name = "vagrant-mgmt"
                domain.management_network_address = "10.5.11.0/24"
                domain.management_network_autostart
            end
    
            vmdef.vm.provision "shell", inline: <<-SHELL
                echo "$(date +%Y-%m-%d.%H-%M.UTC) : $HOSTNAME booted up" >> /matrix/logs
                RUNNEX=/matrix/runnex; ${RUNNEX} &>> ${RUNNEX}.${HOSTNAME}
            SHELL
        end
    end
end
