apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    name: ''
    namespace: argospace-grafana
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.43.4
    helm:
      valueFiles:
        - values.yaml
      values: '{adminPassword: "strongpassword"}'
    chart: grafana
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

