#!/bin/bash -e

# ----
DKR_DNS=8.8.8.8
PUBLISH=3000
DATUM_DIR=datum
DASHBOARD_DIR=$DATUM_DIR/dashboard
GRAFANA_URL=http://172.17.0.1:3000
API_KEY=$(< $DATUM_DIR/tmp.api_key)
# ----
source .properd/VARSET
# ----

function curl_get(){
    local api_path=$1
    curl -s -H "Authorization: Bearer $API_KEY"  ${GRAFANA_URL}$api_path
}



DASHBOARD=$(curl_get /api/search | jq -r '.[] | .uid +":"+ .uri')

for i in $DASHBOARD ; do
    uid=$(echo $i | awk -F ":" '{print $1}')
    uri=$(echo $i | awk -F ":" '{print $2}')
    mkdir -p $DASHBOARD_DIR/$(dirname $uri)
    curl_get /api/dashboards/uid/$uid | jq '(.dashboard.id) = "null"' > $DASHBOARD_DIR/$uri
done


