#!/bin/bash -e

HOMEPATH=graf
DATA_TREE="
    conf/provisioning/datasources
    conf/provisioning/notifiers
    conf/provisioning/dashboards
    conf/provisioning/plugins
    conf/provisioning/access-control
    plugins-bundled
    data
    data/logs
    data/plugins
"


if ! test -d ${HOMEPATH} ; then
    mkdir -p $HOMEPATH
    cd $HOMEPATH
        mkdir -p $DATA_TREE
        touch conf/defaults.ini
        ln -s /usr/share/grafana/public public
    cd -
fi

HOMEPATH=$(readlink -f $HOMEPATH)
export GF_PATHS_DATA=$HOMEPATH/data
export GF_PATHS_LOGS=$HOMEPATH/logs
export GF_PATHS_PLUGINS=$HOMEPATH/plugins
export GF_PATHS_PROVISIONING=$HOMEPATH/conf/provisioning
grafana-server --homepath="${HOMEPATH}" --config="./grafana.ini"
