apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding


metadata:
    name: crbind-kzq4
    namespace: argocd

subjects:
    - kind: ServiceAccount
      name: argocd-server
      namespace: argocd

roleRef:
    kind: ClusterRole
    name: argocd
    apiGroup: rbac.authorization.k8s.io
