#!/usr/bin/env bash
#set -x
# ---- |EXT ----
VARSET_EXT=$1
# ---- |DEFAULT ----

# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----
MSYS_NO_PATHCONV=1 uvx mcp-proxy --sse-port 9090 --allow-origin '*' -- docker run -i -v $HOME:/home/$(whoami) mcp/dekstop-commander
