#!/bin/bash


NODE=$1
test -z "$NODE" && NODE=10.13.0.101
NAMESPACE=kubernetes-dashboard
SERVICE=nodeport-kubernetes-dashboard
NODEPORT=$( kubectl get service $SERVICE -n $NAMESPACE -o json | jq .spec.ports[0].nodePort )


curl -v -I -k https://$NODE:$NODEPORT/
echo -e "\n| SERVICE-URL | https://$NODE:$NODEPORT/"
