#!/bin/bash -e

ARTIFACT_DIR=$ARTIFACT_DIR/gnome
mkdir -p $ARTIFACT_DIR


VERSION_glib=${ARTIFACT_VERSION}
curl -s -L -o $ARTIFACT_DIR/glib-${VERSION_glib}.tar.xz https://download.gnome.org/sources/glib/2.87/glib-2.87.0.tar.xz


cd $ARTIFACT_DIR
rm -rf INSTALL/glib
mkdir -p INSTALL/glib

tar xf glib-${VERSION_glib}.tar.xz
cd glib-${VERSION_glib}
meson setup tmp_meson --prefix=$(readlink -f ../INSTALL/glib) 
meson compile -C tmp_meson
meson install -C tmp_meson
cd -

mkdir -p ~/.local/lib/gnome-glib
cp -rf INSTALL/glib/lib/* ~/.local/lib/gnome-glib/



