#!/bin/bash -e

ARTIFACT_DIR=$ARTIFACT_DIR/pkgconfig
mkdir -p $ARTIFACT_DIR


VERSION_pkgconfig=${ARTIFACT_VERSION}
curl -s -L -o $ARTIFACT_DIR/pkgconfig-$VERSION_pkgconfig.tar.gz  https://pkgconfig.freedesktop.org/releases/pkg-config-${VERSION_pkgconfig}.tar.gz
cd $ARTIFACT_DIR
rm -rf INSTALL
mkdir -p INSTALL/pkgconfig




tar xf pkgconfig-${VERSION_pkgconfig}.tar.gz
cd pkg-config-$VERSION_pkgconfig
export CFLAGS="-Wno-int-conversion"
export CXXFLAGS="-Wno-int-conversion"
LDFLAGS="-framework CoreFoundation -framework Carbon" ./configure --prefix=$(readlink -f ../INSTALL/pkgconfig) --with-internal-glib ~/.local/lib/gnome-glib/x86-64_linux-gnu/
make install install-exec-hook=
cd -

cp -f INSTALL/pkgconfig/bin/pkg-config ~/.local/bin

