prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: manual
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi
          selector:
            matchLabels:
              type: "local"

