#!/bin/bash
source .properd/VARSET

# ---- install ----
install .vimrc ~/
install .gvimrc ~/
cp -r .vim ~/
install .gitconfig ~/
install .bashrc ~/
install .bashrc.path ~/
install .bash_profile ~/
install .wslconfig ~/
install .terminal.settings.json  "$LOCALAPPDATA/Microsoft/Windows Terminal/settings.json"


# ---- function T
.function/symlink
cd .. && .function/symlink && cd -
#.function/artefact-ready
source ~/.bashrc
test -z "$(yq -V | grep -o mikefarah)" && curl -L -o $LOCAL_BIN/yq "https://github.com/mikefarah/yq/releases/download/v4.45.4/yq_windows_amd64.exe" && chmod 0755 $LOCAL_BIN/yq
