#!/bin/bash
source .properd/VARSET

# ---- install ----
install .vimrc ~/
install .gvimrc ~/
cp -r .vim ~/
install .gitconfig ~/
install .bashrc ~/
install .bash_profile ~/
install .wslconfig ~/
install .ConEmu.xml $APPDATA/ConEmu.xml


# ---- function T
.function/symlink
cd .. && .function/symlink && cd -
#.function/artefact-ready
