#!/bin/bash -x



DKR_ENV=${DKR_ENV:-".env"}

source $DKR_ENV

DKR_IMAGE=${DKR_IMAGE:-"ubuntu:latest"}
CMD=${@:-bash --rcfile /dkr/rc}

MSYS_NO_PATHCONV=1 docker run \
    --rm \
    -it \
    -v "$(pwd):/cpwd" \
    -v "$(pwd)/$DKR_ENV:/dkr/rc" \
    --env-file $DKR_ENV \
    --workdir "/cpwd" \
    $DKR_IMAGE $CMD
