.\.function\env-path-add.ps1 "C:\Program Files\Git\usr\bin"
.\.function\env-path-add.ps1 "C:\Program Files\Git\bin\"
.\.function\env-path-add.ps1 "C:\Program Files (x86)\Vim\vim90\"
.\.function\env-path-add.ps1 "$HOME\.local\bin\"
.\.function\env-path-add.ps1 "$HOME\echo-home\windows\powershell\.function\"
