#!/bin/bash
#
#
NAMESPACE=$1
SERVICEACCOUNT=$2
source .function/varcheck-NAMESPACE
source .function/varcheck-SERVICEACCOUNT


results=$(kubectl  get secret -n $NAMESPACE -o json | \
    jq -r ".items[] 
        | select(.type==\"kubernetes.io/service-account-token\")
        | select(.metadata.annotations.\"kubernetes.io/service-account.name\"==\"$SERVICEACCOUNT\") 
        | .metadata.name + \":\" + .data.token
       "
)


# awk: transform field with external command  ----  { $NAME : $(echo $VALUE | base64 -d) }
# note: result should not have line empty
echo "$results" | awk  -F":"  '
    {
        secret_name=$1 ;
        data_token=$2 ;
        ext_cmd="echo "data_token" | base64 -d";
        ext_cmd | getline base64_decoded ;
        close(ext_cmd)
        print "\n\n"secret_name"  :  "base64_decoded;
    }
'



