#!/bin/bash -e

source .function/rcloner

SUB_FILE_PATH=$1

EXTENT=$(grep -l  $SUB_FILE_PATH .meta/*  | awk -F "/" '{print $2}')

rclone  delete ${EXTENT}${SUB_FILE_PATH}
# Do we want to delete its cache
#rm $VOLUME_CACHE/$SUB_FILE_PATH
.function/mount
echo "SUBPATH DELETED |X|" 
echo $SUB_FILE_PATH
