#!/bin/bash -e

source .function/rcloner

SUB_FILE_PATH=$1

EXTENT=$(basename $(grep -l  $SUB_FILE_PATH $META_DIR/*  | head -1))

mkdir -p $(dirname $VOLUME_CACHE/$SUB_FILE_PATH)
rclone cat ${EXTENT}${SUB_FILE_PATH} > $VOLUME_CACHE/$SUB_FILE_PATH

echo "FILE READY >>" 
echo $(readlink -f $VOLUME_CACHE/$SUB_FILE_PATH)
