#!/bin/bash -e

source .function/rcloner

SUB_PATH=$1
NEW_NAME=$2
EXTENT=$(basename $(grep -l  $SUB_PATH $META_DIR/*  | head -1)  2>/dev/null)

function abort(){
    local msg=$1
    echo $msg
    exit 1
}

rclone ls ${EXTENT}${SUB_PATH} &>/dev/null || abort "SOURCE IS NOT EXISTING"
rclone ls ${EXTENT}$(dirname $SUB_PATH)/${NEW_NAME} &>/dev/null  &&  abort "DEST IS EXISTING ALREADY"

rclone moveto ${EXTENT}${SUB_PATH}    ${EXTENT}$(dirname $SUB_PATH)/${NEW_NAME}
rclone ls $EXTENT > $META_DIR/$EXTENT

echo "SUBPATH RENAMED |RN|" 
echo "${EXTENT}$(dirname $SUB_PATH)/${NEW_NAME}"

