#!/usr/bin/env bash
#set -x
# ---- |EXT ----
VARSET_EXT=$1
# ---- |DEFAULT ----

# ---- |OVERRIDE ----
source .properd/VARSET
test -n "$VARSET_EXT" && source $VARSET_EXT

# ---- |MAIN ----

export GOOGLE_GEMINI_BASE_URL=http://localhost:4000
export GEMINI_API_KEY="localm"

gemini --sandbox=false -m gemini-2.5-pro
